USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_D_FORNECEDOR') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_D_FORNECEDOR
	PRINT '<< DROP PROCEDURE dbo.PROC_D_FORNECEDOR >>'
END
GO

CREATE PROCEDURE dbo.PROC_D_FORNECEDOR
	  @IdFornecedor				INT
AS
BEGIN
	DELETE FROM dbo.Fornecedor
	WHERE 
			IdFornecedor = @IdFornecedor
END
GO

IF OBJECT_ID('dbo.PROC_D_FORNECEDOR') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_D_FORNECEDOR >>'
END
GO