USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_D_PEDIDO') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_D_PEDIDO
	PRINT '<< DROP PROCEDURE dbo.PROC_D_PEDIDO >>'
END
GO

CREATE PROCEDURE dbo.PROC_D_PEDIDO
	  @IdPedido					INT
AS
BEGIN
	DELETE dbo.Pedido
	WHERE 
			IdPedido = @IdPedido
END
GO

IF OBJECT_ID('dbo.PROC_D_PEDIDO') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_D_PEDIDO >>'
END
GO