USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_D_CATEGORIA') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_D_CATEGORIA
	PRINT '<< DROP PROCEDURE dbo.PROC_D_CATEGORIA >>'
END
GO

CREATE PROCEDURE dbo.PROC_D_CATEGORIA
	  @IdMarca					INT
	, @IdCategoria				INT
AS
BEGIN
	DELETE FROM dbo.Categoria
	WHERE 
			IdMarca = @IdMarca
		AND IdCategoria = @IdCategoria
END
GO

IF OBJECT_ID('dbo.PROC_D_CATEGORIA') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_D_CATEGORIA >>'
END
GO