USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_D_CLIENTE') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_D_CLIENTE
	PRINT '<< DROP PROCEDURE dbo.PROC_D_CLIENTE >>'
END
GO

CREATE PROCEDURE dbo.PROC_D_CLIENTE
	  @IdCliente			INT
AS
BEGIN
	DELETE FROM dbo.Cliente
	WHERE 
			IdCliente = @IdCliente
END
GO

IF OBJECT_ID('dbo.PROC_D_CLIENTE') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_D_CLIENTE >>'
END
GO