USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_D_MARCA') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_D_MARCA
	PRINT '<< DROP PROCEDURE dbo.PROC_D_MARCA >>'
END
GO

CREATE PROCEDURE dbo.PROC_D_MARCA
	  @IdMarca					INT
AS
BEGIN
	DELETE FROM dbo.Marca
	WHERE 
			IdMarca = @IdMarca
END
GO

IF OBJECT_ID('dbo.PROC_D_MARCA') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_D_MARCA >>'
END
GO