USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_S_FORNECEDOR') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_S_FORNECEDOR
	PRINT '<< DROP PROCEDURE dbo.PROC_S_FORNECEDOR >>'
END
GO

CREATE PROCEDURE dbo.PROC_S_FORNECEDOR
	  @IdFornecedor				INT	= NULL
AS
BEGIN
	SELECT *
	FROM dbo.Fornecedor
	WHERE 
			((@IdFornecedor IS NULL) OR (IdFornecedor = @IdFornecedor))
END
GO

IF OBJECT_ID('dbo.PROC_S_FORNECEDOR') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_S_FORNECEDOR >>'
END
GO