USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_S_MARCA') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_S_MARCA
	PRINT '<< DROP PROCEDURE dbo.PROC_S_MARCA >>'
END
GO

CREATE PROCEDURE dbo.PROC_S_MARCA
	  @IdMarca					INT	= NULL
AS
BEGIN
	SELECT *
	FROM dbo.Marca
	WHERE 
			((@IdMarca IS NULL) OR (IdMarca = @IdMarca))
END
GO

IF OBJECT_ID('dbo.PROC_S_MARCA') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_S_MARCA >>'
END
GO