USE ESTOQUE
GO

IF OBJECT_ID('dbo.PROC_S_CLIENTE') IS NOT NULL
BEGIN
	DROP PROCEDURE dbo.PROC_S_CLIENTE
	PRINT '<< DROP PROCEDURE dbo.PROC_S_CLIENTE >>'
END
GO

CREATE PROCEDURE dbo.PROC_S_CLIENTE
	  @IdCliente			INT	= NULL
AS
BEGIN
	SELECT *
	FROM dbo.Cliente
	WHERE 
			((@IdCliente IS NULL) OR (IdCliente = @IdCliente))
END
GO

IF OBJECT_ID('dbo.PROC_S_CLIENTE') IS NOT NULL
BEGIN
	PRINT '<< CREATE PROCEDURE dbo.PROC_S_CLIENTE >>'
END
GO